version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stealth_gas_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - stealth_gas_net
    ports:
      - "5432:5432"
    volumes:
      - stealth_gas_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stealth_gas_app
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stealth_gas_net
    ports:
      - "8000:8000"

networks:
  stealth_gas_net:
    driver: bridge

volumes:
  stealth_gas_db_data:
